### ISSUE TITLE
i need contact me

### ISSUE THREAD

**Issue by Brayan-Villa** [DuffyAPP-IT/MH_Connect#8]
Hello bro! i check your job with iOS Security ¡Awesome!
Sorry for my bad english, my languaje is spanish.
I want to propose something that I am sure you will be very interested in, it is something I am currently working on.
Please, if it is of your interest, contact me by telegram: +52 477 555 1396

**Comment by DuffyAPP-IT** [comment]
Good-morning 😊. I hope this message finds you well today. That's okay! Sure. I don't have Telegram but my e-mail is always accessible - [public@duffy.app](mailto:public@duffy.app) - I look forward to hearing from you soon!
